"""add SemesterPattern model

Revision ID: b74afecb525d
Revises: 
Create Date: 2026-06-29 13:39:41.841244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74afecb525d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester_pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('joining_year', sa.Integer(), nullable=False),
    sa.Column('exam_name', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_supply', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('joining_year', 'exam_name', 'semester', 'is_supply', name='uq_pattern')
    )
    with op.batch_alter_table('semester_pattern', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semester_pattern_joining_year'), ['joining_year'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('regd_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('regd_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('semester_pattern', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semester_pattern_joining_year'))

    op.drop_table('semester_pattern')
    # ### end Alembic commands ###
