"""add google_id and password_changed_at

Revision ID: f6bb571bd812
Revises: b74afecb525d
Create Date: 2026-07-01 10:56:59.884290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bb571bd812'
down_revision = 'b74afecb525d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_google_id')
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.create_index('ix_user_google_id', ['google_id'], unique=True)

    # ### end Alembic commands ###
